language:
  - c
compiler:
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libxxf86vm-dev libxrandr-dev liblua5.2-dev
  - sudo apt-get install mingw-w64 gcc-mingw-w64-base gcc-mingw-w64 binutils-mingw-w64
script:
  - make
  - ./cross-make-mingw.sh
cache:
  - apt
deploy:
  provider: releases
  api_key:
    secure: 3j8Y8FC6bhx8U+m7jB9CX8P3BPeKHyxNUdpt2GNchIHA5C3vuHomck0MmxSWJNJyAoqT6bxGWxPIoIZneye0jCG0mA4VYDtCE6vfMDKxAmrJWMosDFIK47zlbV7DpLETA4a5qC23l8O313aKBJuapmvYYGzK0ZXwJvRapxFr6tE=
  file:
    - build/release-linux-x86_64/Quake3-UrT-Clear-Ded.x86_64
    - build/release-linux-x86_64/Quake3-UrT-Clear.x86_64
    - build/release-mingw32-x86/Quake3-UrT-Clear-Ded.x86.exe
    - build/release-mingw32-x86/Quake3-UrT-Clear.x86.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  on_success: always
  on_failure: always
